/**:
  ros__parameters:
    
    # Signal acquisition
    n_channels: 7
    src: 'plughw:4,0'
    sample_rate: 48000
    hop_size: 48000
    frame_size: 48000 # publish 1 second every second
    microphone_frame_id: 'kinect_frame'
    array_info_path: 'config/kinect_array.yaml'

    # Sound source localization
    speed_sound: 343.
    n_sources: 2
    n_fft: 512
    f_min: 300
    f_max: 8000
    array_x_pos: [0.0, 0.04, 0.02, -0.02, -0.04, -0.02, 0.02]
    array_y_pos: [0.0, 0.0, -0.03464, -0.03464, 0.0, 0.03464, 0.03464]

    ssl_algo: 'MUSIC'

    # Speech recognition